-d /Volumes/mfrey/Documents/RISCV/TangNano-9K-example/picotiny/project/impl/gwsynthesis/picotiny.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /Volumes/mfrey/Documents/RISCV/TangNano-9K-example/picotiny/project/picotiny.cst
-cfg /Volumes/mfrey/Documents/RISCV/TangNano-9K-example/picotiny/project/impl/pnr/device.cfg
-sdc /Volumes/mfrey/Documents/RISCV/TangNano-9K-example/picotiny/project/picotiny.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
